name: deploy and lint

on:
  push:
    branches: ["main", "gitflow", "readPage"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run remote command via SSH
        uses: invi5H/ssh-action@v1
        id: ssh
        with:
          SSH_HOST: ${{ secrets.IP_SERVER }}
          SSH_PORT: 22
          SSH_USER: ${{ secrets.USERNAME_SERVER }}
          SSH_KEY: ${{ secrets.RSA_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd  
          # command: |
          #   cd /home/backend/gnss-radar
          #   docker-compose down
          #   docker pull alfaiv/gnss-radar:latest
          #   docker-compose up